In [28]:
# Save cleaned dataset
df.to_csv("../data/processed/players_clean.csv", index=False)

print("✅ Clean dataset saved successfully!")

✅ Clean dataset saved successfully!

In [27]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   nationality                  814 non-null    object
 1   fifa_ranking                 814 non-null    int64
 2   national_team_kit_sponsor    814 non-null    object
 3   position                     814 non-null    object
 4   national_team_jersey_number  813 non-null    float64
 5   player_dob                   814 non-null    object
 6   club                         814 non-null    object
 7   player_name                  814 non-null    object
 8   appearances                  661 non-null    float64
 9   goals_scored                 584 non-null    float64
 10  assists_provided             584 non-null    float64
 11  dribbles_per_90              563 non-null    float64
 12  interceptions_per_90         563 non-null    float64
 13  tackles_per_90               555 non-null    float64
 14  total_duels_won_per_90       533 non-null    float64
 15  save_percentage              38 non-null     float64
 16  clean_sheets                 38 non-null     float64
 17  brand_sponsor_brand_used     814 non-null    object
dtypes: float64(10), int64(1), object(7)
memory usage: 114.6+ KB

nationality                      0
fifa_ranking                     0
national_team_kit_sponsor        0
position                         0
national_team_jersey_number      1
player_dob                       0
club                             0
player_name                      0
appearances                    153
goals_scored                   230
assists_provided               230
dribbles_per_90                251
interceptions_per_90           251
tackles_per_90                 259
total_duels_won_per_90         281
save_percentage                776
clean_sheets                   776
brand_sponsor_brand_used         0
dtype: int64

In [26]:
text_columns = [
    "national_team_kit_sponsor",
    "brand_sponsor_brand_used"
]

for col in text_columns:
    df[col] = df[col].fillna("Unknown")

In [25]:
numeric_columns = [
    "fifa_ranking",
    "national_team_jersey_number",
    "appearances",
    "goals_scored",
    "assists_provided",
    "dribbles_per_90",
    "interceptions_per_90",
    "tackles_per_90",
    "total_duels_won_per_90",
    "save_percentage",
    "clean_sheets"
]

for col in numeric_columns:
    if col in ["save_percentage", "clean_sheets"]:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace("%", "", regex=False)
            .replace("-", np.nan)
        )

    df[col] = pd.to_numeric(df[col], errors="coerce")

In [24]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("/", "_")
)

df.columns

Index(['nationality', 'fifa_ranking', 'national_team_kit_sponsor', 'position',
       'national_team_jersey_number', 'player_dob', 'club', 'player_name',
       'appearances', 'goals_scored', 'assists_provided', 'dribbles_per_90',
       'interceptions_per_90', 'tackles_per_90', 'total_duels_won_per_90',
       'save_percentage', 'clean_sheets', 'brand_sponsor_brand_used'],
      dtype='object')

In [23]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [22]:
df.describe()

       FIFA Ranking   National Team Jersey Number
count     814.000000                   813.000000
mean       21.713759                    13.507995
std        16.159655                     7.523788
min         1.000000                     1.000000
25%         9.000000                     7.000000
50%        18.000000                    14.000000
75%        29.000000                    20.000000
max        60.000000                    26.000000

In [21]:
df.isnull().sum()

Nationality                    0
FIFA Ranking                   0
National Team Kit Sponsor      1
Position                       0
National Team Jersey Number    1
Player DOB                     0
Club                           0
Player Name                    0
 Appearances                   0
Goals Scored                   1
Assists Provided               1
Dribbles per 90                1
Interceptions per 90           1
Tackles per 90                 1
Total Duels Won per 90         1
Save Percentage                2
Clean Sheets                   0
Brand Sponsor/Brand Used       1
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Nationality                  814 non-null    object
 1   FIFA Ranking                 814 non-null    int64
 2   National Team Kit Sponsor    813 non-null    object
 3   Position                     814 non-null    object
 4   National Team Jersey Number  813 non-null    float64
 5   Player DOB                   814 non-null    object
 6   Club                         814 non-null    object
 7   Player Name                  814 non-null    object
 8    Appearances                 814 non-null    object
 9   Goals Scored                 813 non-null    object
 10  Assists Provided             813 non-null    object
 11  Dribbles per 90              813 non-null    object
 12  Interceptions per 90         813 non-null    object
 13  Tackles per 90               813 non-null    object
 14  Total Duels Won per 90       813 non-null    object
 15  Save Percentage              812 non-null    object
 16  Clean Sheets                 814 non-null    object
 17  Brand Sponsor/Brand Used     813 non-null    object
dtypes: float64(1), int64(1), object(16)
memory usage: 114.6+ KB

In [19]:
print(df.columns.tolist())

['Nationality ', 'FIFA Ranking ', 'National Team Kit Sponsor', 'Position', 'National Team Jersey Number', 'Player DOB', 'Club ', 'Player Name ', ' Appearances', 'Goals Scored ', 'Assists Provided ', 'Dribbles per 90', 'Interceptions per 90', 'Tackles per 90', 'Total Duels Won per 90', 'Save Percentage', 'Clean Sheets', 'Brand Sponsor/Brand Used']

In [18]:
print("Rows, Columns:", df.shape)

Rows, Columns: (814, 18)

In [17]:
# Load the dataset
df = pd.read_csv("../data/raw/FIFA WC 2022 Players Stats.csv")

# Show the first 5 rows
df.head()

,Nationality,FIFA Ranking,National Team Kit Sponsor,Position,National Team Jersey Number,Player DOB,Club,Player Name,Appearances,Goals Scored,Assists Provided,Dribbles per 90,Interceptions per 90,Tackles per 90,Total Duels Won per 90,Save Percentage,Clean Sheets,Brand Sponsor/Brand Used
0,Argentina,2,Adidas,GK,23.0,"Sep 2, 1992",Aston Villa,Emiliano Martinez,7,0,0,0.00,0.00,0.00,0.65,46.67%,43%,Adidas
1,Argentina,2,Adidas,GK,1.0,"Oct 16, 1986",River,Franco Armani,0,-,-,-,-,-,-,-,-,Nike
2,Argentina,2,Adidas,GK,12.0,"May 20, 1992",Villarreal,Geronimo Rulli,0,-,-,-,-,-,-,-,-,Adidas
3,Argentina,2,Adidas,DF,19.0,"Feb 12, 1988",Benfica,Nicolas Otamendi,7,0,1,0.33,1.17,1.30,7.17,-,-,Nike
4,Argentina,2,Adidas,DF,8.0,"Oct 28, 1991",Sevilla,Marcos Acuna,6,0,0,1.45,0.48,2.90,7.97,-,-,Nike

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Show all columns
pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!